name : Upload website to S3
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
    with:
      args: --acl public-read --follow-symlinks --delete
    env:
      AWS_S3_BUCKET: ${{ secrets.AWSS3BUCKET}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEYID}}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWSSECRETACCESSKEYID}}
      AWS_REGION: 'us-east-1'
      SOURCE_DIR: 'aws-cloud-resume-challenge'
